export { default as BlockQuote } from './block-quote'
export { default as Code } from './code'
export { default as H1 } from './h1'
export { default as H2 } from './h2'
export { default as H3 } from './h3'
export { default as H4 } from './h4'
export { default as P } from './p'
export { default } from './p'
export { default as Large } from './large'
export { default as Lead } from './lead'
export { default as Muted } from './muted'
export { default as Small } from './small'
